/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.util.Observer;
import ni.edu.uni.programacion.controllers.PnlVehicleController;
import ni.edu.uni.programacion.controllers.PnlVehicleShowController;
import ni.edu.uni.programacion.views.panels.PnlVehicle;
import ni.edu.uni.programacion.views.panels.PnlShow;

/**
 *
 * @author Sistemas-09
 */
public class DialogVehicle extends javax.swing.JDialog {

    private PnlVehicle pnlVehicle;
    private PnlVehicleController pnlVehicleController;
    PnlShow pnlShow=null;
    PnlVehicleShowController showController=null;

    /**
     * Creates new form DialogVehicle
     */
    public DialogVehicle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
    public void addObserver(Observer ob){
        pnlVehicleController.addObserver(ob);
    }
    
    public PnlShow getPnlShow() {
        return pnlShow;
    }

    public PnlVehicleShowController getPnlShowController() {
        return showController;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Vehicle");

        pnlContent.setLayout(new java.awt.BorderLayout());
        addWindowListener(new java.awt.event.WindowAdapter()
            {
                public void windowClosing(java.awt.event.WindowEvent evt)
                {
                    formWindowClosing(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt)
                {
                    formWindowOpened(evt);
                }
            });
            pnlVehicle = new PnlVehicle();
            try{
                pnlVehicleController = new PnlVehicleController(pnlVehicle);
            }catch(FileNotFoundException e){
            }
            pnlVehicleController.setIsNew(true);
            pnlContent.add(pnlVehicle, BorderLayout.CENTER);
            getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

            getAccessibleContext().setAccessibleName("Add Vehicle");

            setBounds(0, 0, 400, 600);
        }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt)                                  
    {                                      
        getData();
    }                                 

    private void formWindowClosing(java.awt.event.WindowEvent evt)                                   
    {                                       
        
    } 
    public void setPnlShowReference(PnlShow pnlShow, PnlVehicleShowController showController)
    {
        this.pnlShow = pnlShow;
        this.showController = showController;
        
        if(pnlShow== null)
            return;
    }
    public void getData() {
        if(pnlShow == null)
            return;
        int row = pnlShow.getTblShow().getSelectedRow();
        getData(row);
    }
    public void getData(int row) {

        pnlVehicle.getTxtStock().setText(pnlShow.getTblShow().getValueAt(row, 0).toString().trim());
        pnlVehicle.getSpnYear().setValue(pnlShow.getTblShow().getValueAt(row, 1));
        pnlVehicle.getCmbMake().setSelectedItem(pnlShow.getTblShow().getValueAt(row, 2).toString().trim());
        pnlVehicle.getCmbModel().setSelectedItem(pnlShow.getTblShow().getValueAt(row, 3).toString().trim());
        pnlVehicle.getTxtStyle().setText(pnlShow.getTblShow().getValueAt(row, 4).toString().trim());
        pnlVehicle.getFmtVin().setText(pnlShow.getTblShow().getValueAt(row, 5).toString().trim());
        pnlVehicle.getCmbEColor().setSelectedItem(pnlShow.getTblShow().getValueAt(row, 6).toString().trim());
        pnlVehicle.getCmbIColor().setSelectedItem(pnlShow.getTblShow().getValueAt(row, 7).toString().trim());
        Integer miles = Integer.parseInt(pnlShow.getTblShow().getValueAt(row, 8).toString());
        Double price = Double.parseDouble(pnlShow.getTblShow().getValueAt(row, 9).toString());
        pnlVehicle.getSpnMiles().getModel().setValue(miles);
        pnlVehicle.getSpnPrice().getModel().setValue(price);
        
        if(pnlShow.getTblShow().getValueAt(row, 10).toString() == "AUTOMATIC")
            pnlVehicle.getBtngTrans().setSelected(pnlVehicle.getRbtnAut().getModel(), true);
        else
            pnlVehicle.getBtngTrans().setSelected(pnlVehicle.getRbtnMan().getModel(), true);
        pnlVehicle.getTxtEngine().setText(pnlShow.getTblShow().getValueAt(row, 11).toString().trim());
        pnlVehicle.getTxtImage().setText(pnlShow.getTblShow().getValueAt(row, 12).toString().trim());
        pnlVehicle.getCmbStatus().setSelectedItem(pnlShow.getTblShow().getValueAt(row, 13).toString().trim());
        
        int vehicleId = showController.getVehicles().get(row).getId();

        pnlVehicleController.setVehicleIdToEdit(vehicleId);
        pnlVehicleController.setIsUpdate(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogVehicle dialog = new DialogVehicle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
